addCommandAlias("a", "alias")
addCommandAlias("?", "help")
addCommandAlias("h", "!:")
addCommandAlias("r", "reloadQuick")
addCommandAlias("rl", "reload")
addCommandAlias("c", "~compile")
addCommandAlias("tc", "~Test/compile")
addCommandAlias("t", "~test")
addCommandAlias("to", "~testOnly")
addCommandAlias("rm", "~runMain")
addCommandAlias("sv", "scalaVersion")
addCommandAlias("so", """eval println("show scalacOptions ..."); show scalacOptions""")
addCommandAlias("ps", "projects")
addCommandAlias("p", "project")

addCommandAlias("ld", "libraryDependencies")
addCommandAlias("du", "dependencyUpdates")
addCommandAlias("dl", "dependencyList")
addCommandAlias("dt", "dependencyTree")

addCommandAlias("l", "sh ls -l")
addCommandAlias("la", "sh ls -al")
addCommandAlias("cl", "sh clear")

addCommandAlias("g", "git")
addCommandAlias("gst", "git status")
addCommandAlias("gph", "git push")
addCommandAlias("gh", "git hist")
addCommandAlias("gcm", "git commit -m")
addCommandAlias("gcam", "git commit -a -m")
